;SC163::Ctrl ;Fn按键替换Ctrl，但问题在于Fn键的硬件优先级极高，Fn的组合键响应一定会响应，若没有对应响应才则给出Ctrl的响应。
;KeyHistory
; 把 SC163 当作 Ctrl 键使用
SC163 & a::Send "{Ctrl down}a{Ctrl up}"
SC163 & b::Send "{Ctrl down}b{Ctrl up}"
SC163 & c::Send "{Ctrl down}c{Ctrl up}"
SC163 & d::Send "{Ctrl down}d{Ctrl up}"
SC163 & e::Send "{Ctrl down}e{Ctrl up}"
SC163 & f::Send "{Ctrl down}f{Ctrl up}"
SC163 & g::Send "{Ctrl down}g{Ctrl up}"
SC163 & h::Send "{Ctrl down}h{Ctrl up}"
SC163 & i::Send "{Ctrl down}i{Ctrl up}"
SC163 & j::Send "{Ctrl down}j{Ctrl up}"
SC163 & k::Send "{Ctrl down}k{Ctrl up}"
SC163 & l::Send "{Ctrl down}l{Ctrl up}"
SC163 & m::Send "{Ctrl down}m{Ctrl up}"
SC163 & n::Send "{Ctrl down}n{Ctrl up}"
SC163 & o::Send "{Ctrl down}o{Ctrl up}"
SC163 & p::Send "{Ctrl down}p{Ctrl up}"
SC163 & q::Send "{Ctrl down}q{Ctrl up}"
SC163 & r::Send "{Ctrl down}r{Ctrl up}"
SC163 & s::Send "{Ctrl down}s{Ctrl up}"
SC163 & t::Send "{Ctrl down}t{Ctrl up}"
SC163 & u::Send "{Ctrl down}u{Ctrl up}"
SC163 & v::Send "{Ctrl down}v{Ctrl up}"
SC163 & w::Send "{Ctrl down}w{Ctrl up}"
SC163 & x::Send "{Ctrl down}x{Ctrl up}"
SC163 & y::Send "{Ctrl down}y{Ctrl up}"
SC163 & z::Send "{Ctrl down}z{Ctrl up}"
; 数字 0–9（非小键盘）略
