;SC178::Ctrl ;Fn按键替换Ctrl，但问题在于Fn键的硬件优先级极高，Fn的组合键响应一定会响应，若没有对应响应才则给出Ctrl的响应。
;KeyHistory
; 把 SC178 当作 Ctrl 键使用
SC178 & a::Send "{Ctrl down}a{Ctrl up}"
SC178 & b::Send "{Ctrl down}b{Ctrl up}"
SC178 & c::Send "{Ctrl down}c{Ctrl up}"
SC178 & d::Send "{Ctrl down}d{Ctrl up}"
SC178 & e::Send "{Ctrl down}e{Ctrl up}"
SC178 & f::Send "{Ctrl down}f{Ctrl up}"
SC178 & g::Send "{Ctrl down}g{Ctrl up}"
SC178 & h::Send "{Ctrl down}h{Ctrl up}"
SC178 & i::Send "{Ctrl down}i{Ctrl up}"
SC178 & j::Send "{Ctrl down}j{Ctrl up}"
SC178 & k::Send "{Ctrl down}k{Ctrl up}"
SC178 & l::Send "{Ctrl down}l{Ctrl up}"
SC178 & m::Send "{Ctrl down}m{Ctrl up}"
SC178 & n::Send "{Ctrl down}n{Ctrl up}"
SC178 & o::Send "{Ctrl down}o{Ctrl up}"
SC178 & p::Send "{Ctrl down}p{Ctrl up}"
SC178 & q::Send "{Ctrl down}q{Ctrl up}"
SC178 & r::Send "{Ctrl down}r{Ctrl up}"
SC178 & s::Send "{Ctrl down}s{Ctrl up}"
SC178 & t::Send "{Ctrl down}t{Ctrl up}"
SC178 & u::Send "{Ctrl down}u{Ctrl up}"
SC178 & v::Send "{Ctrl down}v{Ctrl up}"
SC178 & w::Send "{Ctrl down}w{Ctrl up}"
SC178 & x::Send "{Ctrl down}x{Ctrl up}"
SC178 & y::Send "{Ctrl down}y{Ctrl up}"
SC178 & z::Send "{Ctrl down}z{Ctrl up}"
; 数字 0–9（非小键盘）略
